paths:
  /api/products:
    get:
      summary: Devuelve todos los products - Incluye filters
      tags:
        - Products
      responses:
        "200":
          description: Operación resuelta con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error en el servidor

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: ObjectId
          description: ID del producto - (generado por Mongo)
        title:
          type: String
          description: Titulo del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Codigo unico del producto
        stock:
          type: Number
          description: Stock del producto - (Cantidad de unidades)
        category:
          type: String
          description: Categoria del producto
        owner:
          type: ObjectId
          description: ID del creador del producto - (generado por Mongo)
        thumbnails:
          type: Array
          items:
            type: String
      example:
        id: 663bfc3d74aa17e7412cf919
        code: 1
        price: 29388
        status: true
        stock: 2
        category: electronic
        thumbnails: [
            "https://http2.mlstatic.com/D_NQ_NP_677855-MLA71570451917_092023-O.webp"
        ]
        owner: 664a5c70db6a15f01754bd6b
